project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Submission Material"
  description: "Course Projects for STA 9750 at Baruch College"
  site-url: "https://shaddokd.github.io/STA9750-2025-FALL/"
  navbar:
    background: primary
    search: false
    right:
      - href: index.qmd
        text: Home
      - href: mp01.qmd
        text: Mini Project One
      - href: mp02.qmd
        text: Mini Project Two
      - href: mp03.qmd
        text: Mini Project Three
      - href: mp04.qmd
        text: Mini Project Four
      - text: Final Project
        menu:
          - href: gp01.qmd
            text: Project Overview
          - href: GS01.qmd
            text: Summary Report
          - href: gp01-individual.qmd
            text: Individual Report

format:
  html:
    theme: lux
    toc: true
    toc-location: left
    code-fold: true
    code-summary: "Show code"

editor:
  mode: source